# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(default=''),
        ),
    ]
