# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170819_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 19, 15, 41, 55, 482734)),
        ),
    ]
